sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_USER: d180cf
  - GH_REPO: d180cf.github.io
  - secure: ILEe4ucTC9dKct0fYzyPtuf8a/8Bo8U4Pr/e4O34QUNadPGaVBYhU2fnZxZuf1YdHTHZqmbwww6yvCOsOPG5UkcVmYThSOnAoE5W3MjsNkKpmhYosfkksdp0lV6RNoD0gmPow5PZ9Z02IG07nk7D8PlWl2N4YH6DnW05DXWk3LkqsjiNXem7XdA3d75aJ4OPkYVRyhwHm6LD6a8+fUklRDxz/YWuL4PX9fm/IJyeM96SAgowQwio0F7lN2kIuqY/NHS4PYleiD136LF62mrlmdS8+KzGwprWngAEI1vMabTZYwO8AzEXCHHIoSyD2Kee7Osz+42beARi0YXK9GlBFCl/VVd7hSDYGXwl56b53k52Cd+bOWC0IKFMidwbDcQgtIlzw1/gZWl1M1f6oVpLX1BeD2mU6g8ips8R+Ola2H2OBUOZWigkaxPJm+Xek+YJu60rGo270YljPazdFiyaoZLelcePzMm6guTakakqXsbAoGeCmf9p/2JcgxrUn32aj1mZYA9Uu2wDMmqgiYqGASCaMcMMukU/YutbzoK9WkXtdHDTu+gdR+n82rx39qwen+Bfkq+pJjMAZtSKugCx0Wk0BT+W3X8BKSHIUs7okRb0dDmrcJpN1H3f8Txq8uU6Gy5B7fQNuHsz+BDuc3Ko/CiA3OvwcGQ8WxVYq0GEU3U=
